export interface TechBadge {
  name: string;
  category: "Frontend" | "Backend" | "DevOps" | "Tools";
  badgeUrl: string;
  color: string;
  iconId?: string;
}

export const TECH_BADGES: TechBadge[] = [
  { name: "Android", category: "Tools", badgeUrl: "https://raw.githubusercontent.com/xandemon/developer-icons/main/icons/android.svg", color: "#000000", iconId: "android" },
  { name: "Angular", category: "Frontend", badgeUrl: "https://raw.githubusercontent.com/xandemon/developer-icons/main/icons/angular.svg", color: "#000000", iconId: "angular" },
  { name: "Ansible", category: "DevOps", badgeUrl: "https://raw.githubusercontent.com/xandemon/developer-icons/main/icons/ansible.svg", color: "#000000", iconId: "ansible" },
  { name: "Ansible Wordmark", category: "DevOps", badgeUrl: "https://raw.githubusercontent.com/xandemon/developer-icons/main/icons/ansible-wordmark.svg", color: "#000000", iconId: "ansible-wordmark" },
  { name: "Anthropic", category: "Tools", badgeUrl: "https://raw.githubusercontent.com/xandemon/developer-icons/main/icons/anthropic.svg", color: "#000000", iconId: "anthropic" },
  { name: "Anthropic Basic Dark", category: "Tools", badgeUrl: "https://raw.githubusercontent.com/xandemon/developer-icons/main/icons/anthropic-basic-dark.svg", color: "#000000", iconId: "anthropic-basic-dark" },
  { name: "Anthropic Basic Light", category: "Tools", badgeUrl: "https://raw.githubusercontent.com/xandemon/developer-icons/main/icons/anthropic-basic-light.svg", color: "#000000", iconId: "anthropic-basic-light" },
  { name: "Apache", category: "DevOps", badgeUrl: "https://raw.githubusercontent.com/xandemon/developer-icons/main/icons/apache.svg", color: "#000000", iconId: "apache" },
  { name: "Apple Dark", category: "Tools", badgeUrl: "https://raw.githubusercontent.com/xandemon/developer-icons/main/icons/apple-dark.svg", color: "#000000", iconId: "apple-dark" },
  { name: "Apple Light", category: "Tools", badgeUrl: "https://raw.githubusercontent.com/xandemon/developer-icons/main/icons/apple-light.svg", color: "#000000", iconId: "apple-light" },
  { name: "Appwrite", category: "Backend", badgeUrl: "https://raw.githubusercontent.com/xandemon/developer-icons/main/icons/appwrite.svg", color: "#000000", iconId: "appwrite" },
  { name: "Arc", category: "Tools", badgeUrl: "https://raw.githubusercontent.com/xandemon/developer-icons/main/icons/arc.svg", color: "#000000", iconId: "arc" },
  { name: "Astro", category: "Frontend", badgeUrl: "https://raw.githubusercontent.com/xandemon/developer-icons/main/icons/astro.svg", color: "#000000", iconId: "astro" },
  { name: "Atlassian", category: "Tools", badgeUrl: "https://raw.githubusercontent.com/xandemon/developer-icons/main/icons/atlassian.svg", color: "#000000", iconId: "atlassian" },
  { name: "Atom", category: "Tools", badgeUrl: "https://raw.githubusercontent.com/xandemon/developer-icons/main/icons/atom.svg", color: "#000000", iconId: "atom" },
  { name: "Auth0", category: "Tools", badgeUrl: "https://raw.githubusercontent.com/xandemon/developer-icons/main/icons/auth0.svg", color: "#000000", iconId: "auth0" },
  { name: "Avajs", category: "Tools", badgeUrl: "https://raw.githubusercontent.com/xandemon/developer-icons/main/icons/avajs.svg", color: "#000000", iconId: "avajs" },
  { name: "Aws", category: "DevOps", badgeUrl: "https://raw.githubusercontent.com/xandemon/developer-icons/main/icons/aws.svg", color: "#000000", iconId: "aws" },
  { name: "Axiom", category: "Tools", badgeUrl: "https://raw.githubusercontent.com/xandemon/developer-icons/main/icons/axiom.svg", color: "#000000", iconId: "axiom" },
  { name: "Axure", category: "Tools", badgeUrl: "https://raw.githubusercontent.com/xandemon/developer-icons/main/icons/axure.svg", color: "#000000", iconId: "axure" },
  { name: "Azure", category: "DevOps", badgeUrl: "https://raw.githubusercontent.com/xandemon/developer-icons/main/icons/azure.svg", color: "#000000", iconId: "azure" },
  { name: "Babel", category: "Frontend", badgeUrl: "https://raw.githubusercontent.com/xandemon/developer-icons/main/icons/babel.svg", color: "#000000", iconId: "babel" },
  { name: "Backbonejs", category: "Frontend", badgeUrl: "https://raw.githubusercontent.com/xandemon/developer-icons/main/icons/backbonejs.svg", color: "#000000", iconId: "backbonejs" },
  { name: "Bard", category: "Tools", badgeUrl: "https://raw.githubusercontent.com/xandemon/developer-icons/main/icons/bard.svg", color: "#000000", iconId: "bard" },
  { name: "Bash", category: "DevOps", badgeUrl: "https://raw.githubusercontent.com/xandemon/developer-icons/main/icons/bash.svg", color: "#000000", iconId: "bash" },
  { name: "Bing", category: "Tools", badgeUrl: "https://raw.githubusercontent.com/xandemon/developer-icons/main/icons/bing.svg", color: "#000000", iconId: "bing" },
  { name: "Biome", category: "Tools", badgeUrl: "https://raw.githubusercontent.com/xandemon/developer-icons/main/icons/biome.svg", color: "#000000", iconId: "biome" },
  { name: "Bitbucket", category: "DevOps", badgeUrl: "https://raw.githubusercontent.com/xandemon/developer-icons/main/icons/bitbucket.svg", color: "#000000", iconId: "bitbucket" },
  { name: "Bitnami", category: "DevOps", badgeUrl: "https://raw.githubusercontent.com/xandemon/developer-icons/main/icons/bitnami.svg", color: "#000000", iconId: "bitnami" },
  { name: "Blueprintjs", category: "Frontend", badgeUrl: "https://raw.githubusercontent.com/xandemon/developer-icons/main/icons/blueprintjs.svg", color: "#000000", iconId: "blueprintjs" },
  { name: "Bluesky", category: "Tools", badgeUrl: "https://raw.githubusercontent.com/xandemon/developer-icons/main/icons/bluesky.svg", color: "#000000", iconId: "bluesky" },
  { name: "Bootstrap4", category: "Frontend", badgeUrl: "https://raw.githubusercontent.com/xandemon/developer-icons/main/icons/bootstrap4.svg", color: "#000000", iconId: "bootstrap4" },
  { name: "Bootstrap5", category: "Frontend", badgeUrl: "https://raw.githubusercontent.com/xandemon/developer-icons/main/icons/bootstrap5.svg", color: "#000000", iconId: "bootstrap5" },
  { name: "Brave", category: "Frontend", badgeUrl: "https://raw.githubusercontent.com/xandemon/developer-icons/main/icons/brave.svg", color: "#000000", iconId: "brave" },
  { name: "Bulmaui", category: "Frontend", badgeUrl: "https://raw.githubusercontent.com/xandemon/developer-icons/main/icons/bulmaui.svg", color: "#000000", iconId: "bulmaui" },
  { name: "Bunjs", category: "Backend", badgeUrl: "https://raw.githubusercontent.com/xandemon/developer-icons/main/icons/bunjs.svg", color: "#000000", iconId: "bunjs" },
  { name: "C", category: "Tools", badgeUrl: "https://raw.githubusercontent.com/xandemon/developer-icons/main/icons/c.svg", color: "#000000", iconId: "c" },
  { name: "C++", category: "Tools", badgeUrl: "https://raw.githubusercontent.com/xandemon/developer-icons/main/icons/c-plus-plus.svg", color: "#000000", iconId: "c-plus-plus" },
  { name: "C#", category: "Tools", badgeUrl: "https://raw.githubusercontent.com/xandemon/developer-icons/main/icons/c-sharp.svg", color: "#000000", iconId: "c-sharp" },
  { name: "Cakephp", category: "Backend", badgeUrl: "https://raw.githubusercontent.com/xandemon/developer-icons/main/icons/cakephp.svg", color: "#000000", iconId: "cakephp" },
  { name: "Canva", category: "Tools", badgeUrl: "https://raw.githubusercontent.com/xandemon/developer-icons/main/icons/canva.svg", color: "#000000", iconId: "canva" },
  { name: "Cassandradb", category: "Backend", badgeUrl: "https://raw.githubusercontent.com/xandemon/developer-icons/main/icons/cassandradb.svg", color: "#000000", iconId: "cassandradb" },
  { name: "Chakraui", category: "Frontend", badgeUrl: "https://raw.githubusercontent.com/xandemon/developer-icons/main/icons/chakraui.svg", color: "#000000", iconId: "chakraui" },
  { name: "Chatgpt", category: "Tools", badgeUrl: "https://raw.githubusercontent.com/xandemon/developer-icons/main/icons/chatgpt.svg", color: "#000000", iconId: "chatgpt" },
  { name: "Chrome", category: "Frontend", badgeUrl: "https://raw.githubusercontent.com/xandemon/developer-icons/main/icons/chrome.svg", color: "#000000", iconId: "chrome" },
  { name: "Chromium", category: "Frontend", badgeUrl: "https://raw.githubusercontent.com/xandemon/developer-icons/main/icons/chromium.svg", color: "#000000", iconId: "chromium" },
  { name: "Circleci", category: "DevOps", badgeUrl: "https://raw.githubusercontent.com/xandemon/developer-icons/main/icons/circleci.svg", color: "#000000", iconId: "circleci" },
  { name: "Claude Ai", category: "Tools", badgeUrl: "https://raw.githubusercontent.com/xandemon/developer-icons/main/icons/claude-ai.svg", color: "#000000", iconId: "claude-ai" },
  { name: "Clerk", category: "Tools", badgeUrl: "https://raw.githubusercontent.com/xandemon/developer-icons/main/icons/clerk.svg", color: "#000000", iconId: "clerk" },
  { name: "Clickhouse", category: "Backend", badgeUrl: "https://raw.githubusercontent.com/xandemon/developer-icons/main/icons/clickhouse.svg", color: "#000000", iconId: "clickhouse" },
  { name: "Clojure", category: "Backend", badgeUrl: "https://raw.githubusercontent.com/xandemon/developer-icons/main/icons/clojure.svg", color: "#000000", iconId: "clojure" },
  { name: "Cloudflare", category: "DevOps", badgeUrl: "https://raw.githubusercontent.com/xandemon/developer-icons/main/icons/cloudflare.svg", color: "#000000", iconId: "cloudflare" },
  { name: "Cloudinary", category: "Tools", badgeUrl: "https://raw.githubusercontent.com/xandemon/developer-icons/main/icons/cloudinary.svg", color: "#000000", iconId: "cloudinary" },
  { name: "Codefresh", category: "DevOps", badgeUrl: "https://raw.githubusercontent.com/xandemon/developer-icons/main/icons/codefresh.svg", color: "#000000", iconId: "codefresh" },
  { name: "Codeigniter", category: "Backend", badgeUrl: "https://raw.githubusercontent.com/xandemon/developer-icons/main/icons/codeigniter.svg", color: "#000000", iconId: "codeigniter" },
  { name: "Convex", category: "Backend", badgeUrl: "https://raw.githubusercontent.com/xandemon/developer-icons/main/icons/convex.svg", color: "#000000", iconId: "convex" },
  { name: "Copilot", category: "Tools", badgeUrl: "https://raw.githubusercontent.com/xandemon/developer-icons/main/icons/copilot.svg", color: "#000000", iconId: "copilot" },
  { name: "Crystal", category: "Backend", badgeUrl: "https://raw.githubusercontent.com/xandemon/developer-icons/main/icons/crystal.svg", color: "#000000", iconId: "crystal" },
  { name: "Css", category: "Frontend", badgeUrl: "https://raw.githubusercontent.com/xandemon/developer-icons/main/icons/css.svg", color: "#000000", iconId: "css" },
  { name: "CSS3", category: "Frontend", badgeUrl: "https://raw.githubusercontent.com/xandemon/developer-icons/main/icons/css3.svg", color: "#000000", iconId: "css3" },
  { name: "Cypress", category: "Tools", badgeUrl: "https://raw.githubusercontent.com/xandemon/developer-icons/main/icons/cypress.svg", color: "#000000", iconId: "cypress" },
  { name: "Dart", category: "Backend", badgeUrl: "https://raw.githubusercontent.com/xandemon/developer-icons/main/icons/dart.svg", color: "#000000", iconId: "dart" },
  { name: "Datadog", category: "DevOps", badgeUrl: "https://raw.githubusercontent.com/xandemon/developer-icons/main/icons/datadog.svg", color: "#000000", iconId: "datadog" },
  { name: "Deepseek", category: "Tools", badgeUrl: "https://raw.githubusercontent.com/xandemon/developer-icons/main/icons/deepseek.svg", color: "#000000", iconId: "deepseek" },
  { name: "Deepseek Wordmark", category: "Tools", badgeUrl: "https://raw.githubusercontent.com/xandemon/developer-icons/main/icons/deepseek-wordmark.svg", color: "#000000", iconId: "deepseek-wordmark" },
  { name: "Deno", category: "Backend", badgeUrl: "https://raw.githubusercontent.com/xandemon/developer-icons/main/icons/deno.svg", color: "#000000", iconId: "deno" },
  { name: "Deno Fresh", category: "Backend", badgeUrl: "https://raw.githubusercontent.com/xandemon/developer-icons/main/icons/deno-fresh.svg", color: "#000000", iconId: "deno-fresh" },
  { name: "Developer Icons", category: "Tools", badgeUrl: "https://raw.githubusercontent.com/xandemon/developer-icons/main/icons/developer-icons.svg", color: "#000000", iconId: "developer-icons" },
  { name: "Digitalocean", category: "DevOps", badgeUrl: "https://raw.githubusercontent.com/xandemon/developer-icons/main/icons/digitalocean.svg", color: "#000000", iconId: "digitalocean" },
  { name: "Discord", category: "Tools", badgeUrl: "https://raw.githubusercontent.com/xandemon/developer-icons/main/icons/discord.svg", color: "#000000", iconId: "discord" },
  { name: "Django", category: "Backend", badgeUrl: "https://raw.githubusercontent.com/xandemon/developer-icons/main/icons/django.svg", color: "#000000", iconId: "django" },
  { name: "Dlang", category: "Backend", badgeUrl: "https://raw.githubusercontent.com/xandemon/developer-icons/main/icons/dlang.svg", color: "#000000", iconId: "dlang" },
  { name: "Docker", category: "DevOps", badgeUrl: "https://raw.githubusercontent.com/xandemon/developer-icons/main/icons/docker.svg", color: "#000000", iconId: "docker" },
  { name: "Docusaurus", category: "Frontend", badgeUrl: "https://raw.githubusercontent.com/xandemon/developer-icons/main/icons/docusaurus.svg", color: "#000000", iconId: "docusaurus" },
  { name: "Dovetail", category: "Tools", badgeUrl: "https://raw.githubusercontent.com/xandemon/developer-icons/main/icons/dovetail.svg", color: "#000000", iconId: "dovetail" },
  { name: "Ec2", category: "DevOps", badgeUrl: "https://raw.githubusercontent.com/xandemon/developer-icons/main/icons/ec2.svg", color: "#000000", iconId: "ec2" },
  { name: "Edge", category: "Frontend", badgeUrl: "https://raw.githubusercontent.com/xandemon/developer-icons/main/icons/edge.svg", color: "#000000", iconId: "edge" },
  { name: "Elastic", category: "Backend", badgeUrl: "https://raw.githubusercontent.com/xandemon/developer-icons/main/icons/elastic.svg", color: "#000000", iconId: "elastic" },
  { name: "Electron", category: "Tools", badgeUrl: "https://raw.githubusercontent.com/xandemon/developer-icons/main/icons/electron.svg", color: "#000000", iconId: "electron" },
  { name: "Elementui", category: "Frontend", badgeUrl: "https://raw.githubusercontent.com/xandemon/developer-icons/main/icons/elementui.svg", color: "#000000", iconId: "elementui" },
  { name: "Elixir", category: "Backend", badgeUrl: "https://raw.githubusercontent.com/xandemon/developer-icons/main/icons/elixir.svg", color: "#000000", iconId: "elixir" },
  { name: "Ember", category: "Frontend", badgeUrl: "https://raw.githubusercontent.com/xandemon/developer-icons/main/icons/ember.svg", color: "#000000", iconId: "ember" },
  { name: "Erlang", category: "Backend", badgeUrl: "https://raw.githubusercontent.com/xandemon/developer-icons/main/icons/erlang.svg", color: "#000000", iconId: "erlang" },
  { name: "Esbuild", category: "Tools", badgeUrl: "https://raw.githubusercontent.com/xandemon/developer-icons/main/icons/esbuild.svg", color: "#000000", iconId: "esbuild" },
  { name: "Eslint", category: "Tools", badgeUrl: "https://raw.githubusercontent.com/xandemon/developer-icons/main/icons/eslint.svg", color: "#000000", iconId: "eslint" },
  { name: "Expressjs Dark", category: "Backend", badgeUrl: "https://raw.githubusercontent.com/xandemon/developer-icons/main/icons/expressjs-dark.svg", color: "#000000", iconId: "expressjs-dark" },
  { name: "Expressjs Light", category: "Backend", badgeUrl: "https://raw.githubusercontent.com/xandemon/developer-icons/main/icons/expressjs-light.svg", color: "#000000", iconId: "expressjs-light" },
  { name: "Facebook", category: "Tools", badgeUrl: "https://raw.githubusercontent.com/xandemon/developer-icons/main/icons/facebook.svg", color: "#000000", iconId: "facebook" },
  { name: "Fast API", category: "Tools", badgeUrl: "https://raw.githubusercontent.com/xandemon/developer-icons/main/icons/fast-api.svg", color: "#000000", iconId: "fast-api" },
  { name: "Faunadb", category: "Backend", badgeUrl: "https://raw.githubusercontent.com/xandemon/developer-icons/main/icons/faunadb.svg", color: "#000000", iconId: "faunadb" },
  { name: "Figma", category: "Tools", badgeUrl: "https://raw.githubusercontent.com/xandemon/developer-icons/main/icons/figma.svg", color: "#000000", iconId: "figma" },
  { name: "Firebase", category: "Backend", badgeUrl: "https://raw.githubusercontent.com/xandemon/developer-icons/main/icons/firebase.svg", color: "#000000", iconId: "firebase" },
  { name: "Firefox", category: "Frontend", badgeUrl: "https://raw.githubusercontent.com/xandemon/developer-icons/main/icons/firefox.svg", color: "#000000", iconId: "firefox" },
  { name: "Flask Dark", category: "Backend", badgeUrl: "https://raw.githubusercontent.com/xandemon/developer-icons/main/icons/flask-dark.svg", color: "#000000", iconId: "flask-dark" },
  { name: "Flask Light", category: "Backend", badgeUrl: "https://raw.githubusercontent.com/xandemon/developer-icons/main/icons/flask-light.svg", color: "#000000", iconId: "flask-light" },
  { name: "Flutter", category: "Tools", badgeUrl: "https://raw.githubusercontent.com/xandemon/developer-icons/main/icons/flutter.svg", color: "#000000", iconId: "flutter" },
  { name: "Flyio", category: "DevOps", badgeUrl: "https://raw.githubusercontent.com/xandemon/developer-icons/main/icons/flyio.svg", color: "#000000", iconId: "flyio" },
  { name: "Framer", category: "Frontend", badgeUrl: "https://raw.githubusercontent.com/xandemon/developer-icons/main/icons/framer.svg", color: "#000000", iconId: "framer" },
  { name: "Gatsby", category: "Frontend", badgeUrl: "https://raw.githubusercontent.com/xandemon/developer-icons/main/icons/gatsby.svg", color: "#000000", iconId: "gatsby" },
  { name: "Git", category: "Tools", badgeUrl: "https://raw.githubusercontent.com/xandemon/developer-icons/main/icons/git.svg", color: "#000000", iconId: "git" },
  { name: "Github Copilot", category: "DevOps", badgeUrl: "https://raw.githubusercontent.com/xandemon/developer-icons/main/icons/github-copilot.svg", color: "#000000", iconId: "github-copilot" },
  { name: "Github Dark", category: "DevOps", badgeUrl: "https://raw.githubusercontent.com/xandemon/developer-icons/main/icons/github-dark.svg", color: "#000000", iconId: "github-dark" },
  { name: "Github Light", category: "DevOps", badgeUrl: "https://raw.githubusercontent.com/xandemon/developer-icons/main/icons/github-light.svg", color: "#000000", iconId: "github-light" },
  { name: "Gitlab", category: "DevOps", badgeUrl: "https://raw.githubusercontent.com/xandemon/developer-icons/main/icons/gitlab.svg", color: "#000000", iconId: "gitlab" },
  { name: "Gmail", category: "Tools", badgeUrl: "https://raw.githubusercontent.com/xandemon/developer-icons/main/icons/gmail.svg", color: "#000000", iconId: "gmail" },
  { name: "Go", category: "Tools", badgeUrl: "https://raw.githubusercontent.com/xandemon/developer-icons/main/icons/go.svg", color: "#000000", iconId: "go" },
  { name: "Google", category: "Tools", badgeUrl: "https://raw.githubusercontent.com/xandemon/developer-icons/main/icons/google.svg", color: "#000000", iconId: "google" },
  { name: "Google Cloud", category: "Tools", badgeUrl: "https://raw.githubusercontent.com/xandemon/developer-icons/main/icons/google-cloud.svg", color: "#000000", iconId: "google-cloud" },
  { name: "Google Wordmark", category: "Tools", badgeUrl: "https://raw.githubusercontent.com/xandemon/developer-icons/main/icons/google-wordmark.svg", color: "#000000", iconId: "google-wordmark" },
  { name: "Grafana", category: "DevOps", badgeUrl: "https://raw.githubusercontent.com/xandemon/developer-icons/main/icons/grafana.svg", color: "#000000", iconId: "grafana" },
  { name: "Grafbase", category: "DevOps", badgeUrl: "https://raw.githubusercontent.com/xandemon/developer-icons/main/icons/grafbase.svg", color: "#000000", iconId: "grafbase" },
  { name: "Graphite", category: "DevOps", badgeUrl: "https://raw.githubusercontent.com/xandemon/developer-icons/main/icons/graphite.svg", color: "#000000", iconId: "graphite" },
  { name: "Graphql", category: "Backend", badgeUrl: "https://raw.githubusercontent.com/xandemon/developer-icons/main/icons/graphql.svg", color: "#000000", iconId: "graphql" },
  { name: "Gridsome", category: "Frontend", badgeUrl: "https://raw.githubusercontent.com/xandemon/developer-icons/main/icons/gridsome.svg", color: "#000000", iconId: "gridsome" },
  { name: "Gruntjs", category: "Tools", badgeUrl: "https://raw.githubusercontent.com/xandemon/developer-icons/main/icons/gruntjs.svg", color: "#000000", iconId: "gruntjs" },
  { name: "Gulp", category: "Tools", badgeUrl: "https://raw.githubusercontent.com/xandemon/developer-icons/main/icons/gulp.svg", color: "#000000", iconId: "gulp" },
  { name: "Hashnode", category: "Tools", badgeUrl: "https://raw.githubusercontent.com/xandemon/developer-icons/main/icons/hashnode.svg", color: "#000000", iconId: "hashnode" },
  { name: "Haskell", category: "Backend", badgeUrl: "https://raw.githubusercontent.com/xandemon/developer-icons/main/icons/haskell.svg", color: "#000000", iconId: "haskell" },
  { name: "Headlessui", category: "Frontend", badgeUrl: "https://raw.githubusercontent.com/xandemon/developer-icons/main/icons/headlessui.svg", color: "#000000", iconId: "headlessui" },
  { name: "Heroku", category: "DevOps", badgeUrl: "https://raw.githubusercontent.com/xandemon/developer-icons/main/icons/heroku.svg", color: "#000000", iconId: "heroku" },
  { name: "Hexo", category: "Tools", badgeUrl: "https://raw.githubusercontent.com/xandemon/developer-icons/main/icons/hexo.svg", color: "#000000", iconId: "hexo" },
  { name: "Hhvm", category: "Backend", badgeUrl: "https://raw.githubusercontent.com/xandemon/developer-icons/main/icons/hhvm.svg", color: "#000000", iconId: "hhvm" },
  { name: "Homebrew", category: "Tools", badgeUrl: "https://raw.githubusercontent.com/xandemon/developer-icons/main/icons/homebrew.svg", color: "#000000", iconId: "homebrew" },
  { name: "Hotjar", category: "Tools", badgeUrl: "https://raw.githubusercontent.com/xandemon/developer-icons/main/icons/hotjar.svg", color: "#000000", iconId: "hotjar" },
  { name: "HTML5", category: "Frontend", badgeUrl: "https://raw.githubusercontent.com/xandemon/developer-icons/main/icons/html5.svg", color: "#000000", iconId: "html5" },
  { name: "Hugging Face", category: "Tools", badgeUrl: "https://raw.githubusercontent.com/xandemon/developer-icons/main/icons/hugging-face.svg", color: "#000000", iconId: "hugging-face" },
  { name: "Hyper2", category: "Tools", badgeUrl: "https://raw.githubusercontent.com/xandemon/developer-icons/main/icons/hyper2.svg", color: "#000000", iconId: "hyper2" },
  { name: "I18next", category: "Frontend", badgeUrl: "https://raw.githubusercontent.com/xandemon/developer-icons/main/icons/i18next.svg", color: "#000000", iconId: "i18next" },
  { name: "Indesign", category: "Tools", badgeUrl: "https://raw.githubusercontent.com/xandemon/developer-icons/main/icons/indesign.svg", color: "#000000", iconId: "indesign" },
  { name: "Insomnia", category: "Tools", badgeUrl: "https://raw.githubusercontent.com/xandemon/developer-icons/main/icons/insomnia.svg", color: "#000000", iconId: "insomnia" },
  { name: "Instagram", category: "Tools", badgeUrl: "https://raw.githubusercontent.com/xandemon/developer-icons/main/icons/instagram.svg", color: "#000000", iconId: "instagram" },
  { name: "Internet Explorer", category: "Tools", badgeUrl: "https://raw.githubusercontent.com/xandemon/developer-icons/main/icons/internet-explorer.svg", color: "#000000", iconId: "internet-explorer" },
  { name: "Invision", category: "Tools", badgeUrl: "https://raw.githubusercontent.com/xandemon/developer-icons/main/icons/invision.svg", color: "#000000", iconId: "invision" },
  { name: "Ionic", category: "Frontend", badgeUrl: "https://raw.githubusercontent.com/xandemon/developer-icons/main/icons/ionic.svg", color: "#000000", iconId: "ionic" },
  { name: "Jamstack", category: "Tools", badgeUrl: "https://raw.githubusercontent.com/xandemon/developer-icons/main/icons/jamstack.svg", color: "#000000", iconId: "jamstack" },
  { name: "Java", category: "Backend", badgeUrl: "https://raw.githubusercontent.com/xandemon/developer-icons/main/icons/java.svg", color: "#000000", iconId: "java" },
  { name: "Javascript", category: "Frontend", badgeUrl: "https://raw.githubusercontent.com/xandemon/developer-icons/main/icons/javascript.svg", color: "#000000", iconId: "javascript" },
  { name: "Jenkins", category: "DevOps", badgeUrl: "https://raw.githubusercontent.com/xandemon/developer-icons/main/icons/jenkins.svg", color: "#000000", iconId: "jenkins" },
  { name: "Jest", category: "Tools", badgeUrl: "https://raw.githubusercontent.com/xandemon/developer-icons/main/icons/jest.svg", color: "#000000", iconId: "jest" },
  { name: "Jira", category: "Tools", badgeUrl: "https://raw.githubusercontent.com/xandemon/developer-icons/main/icons/jira.svg", color: "#000000", iconId: "jira" },
  { name: "Jquery", category: "Frontend", badgeUrl: "https://raw.githubusercontent.com/xandemon/developer-icons/main/icons/jquery.svg", color: "#000000", iconId: "jquery" },
  { name: "Jslint", category: "Tools", badgeUrl: "https://raw.githubusercontent.com/xandemon/developer-icons/main/icons/jslint.svg", color: "#000000", iconId: "jslint" },
  { name: "Json", category: "Tools", badgeUrl: "https://raw.githubusercontent.com/xandemon/developer-icons/main/icons/json.svg", color: "#000000", iconId: "json" },
  { name: "Kibana", category: "Tools", badgeUrl: "https://raw.githubusercontent.com/xandemon/developer-icons/main/icons/kibana.svg", color: "#000000", iconId: "kibana" },
  { name: "Kotlin", category: "Backend", badgeUrl: "https://raw.githubusercontent.com/xandemon/developer-icons/main/icons/kotlin.svg", color: "#000000", iconId: "kotlin" },
  { name: "Kubernetes", category: "DevOps", badgeUrl: "https://raw.githubusercontent.com/xandemon/developer-icons/main/icons/kubernetes.svg", color: "#000000", iconId: "kubernetes" },
  { name: "Laravel", category: "Backend", badgeUrl: "https://raw.githubusercontent.com/xandemon/developer-icons/main/icons/laravel.svg", color: "#000000", iconId: "laravel" },
  { name: "Less", category: "Frontend", badgeUrl: "https://raw.githubusercontent.com/xandemon/developer-icons/main/icons/less.svg", color: "#000000", iconId: "less" },
  { name: "Lightroom", category: "Tools", badgeUrl: "https://raw.githubusercontent.com/xandemon/developer-icons/main/icons/lightroom.svg", color: "#000000", iconId: "lightroom" },
  { name: "Linkedin", category: "Tools", badgeUrl: "https://raw.githubusercontent.com/xandemon/developer-icons/main/icons/linkedin.svg", color: "#000000", iconId: "linkedin" },
  { name: "Linux", category: "DevOps", badgeUrl: "https://raw.githubusercontent.com/xandemon/developer-icons/main/icons/linux.svg", color: "#000000", iconId: "linux" },
  { name: "Lit", category: "Frontend", badgeUrl: "https://raw.githubusercontent.com/xandemon/developer-icons/main/icons/lit.svg", color: "#000000", iconId: "lit" },
  { name: "Liveblocks", category: "Tools", badgeUrl: "https://raw.githubusercontent.com/xandemon/developer-icons/main/icons/liveblocks.svg", color: "#000000", iconId: "liveblocks" },
  { name: "Logrocket", category: "Tools", badgeUrl: "https://raw.githubusercontent.com/xandemon/developer-icons/main/icons/logrocket.svg", color: "#000000", iconId: "logrocket" },
  { name: "Lokalise", category: "Tools", badgeUrl: "https://raw.githubusercontent.com/xandemon/developer-icons/main/icons/lokalise.svg", color: "#000000", iconId: "lokalise" },
  { name: "Lua", category: "Backend", badgeUrl: "https://raw.githubusercontent.com/xandemon/developer-icons/main/icons/lua.svg", color: "#000000", iconId: "lua" },
  { name: "Lunacy", category: "Tools", badgeUrl: "https://raw.githubusercontent.com/xandemon/developer-icons/main/icons/lunacy.svg", color: "#000000", iconId: "lunacy" },
  { name: "Mariadb", category: "Backend", badgeUrl: "https://raw.githubusercontent.com/xandemon/developer-icons/main/icons/mariadb.svg", color: "#000000", iconId: "mariadb" },
  { name: "Marionette", category: "Tools", badgeUrl: "https://raw.githubusercontent.com/xandemon/developer-icons/main/icons/marionette.svg", color: "#000000", iconId: "marionette" },
  { name: "Markdown", category: "Tools", badgeUrl: "https://raw.githubusercontent.com/xandemon/developer-icons/main/icons/markdown.svg", color: "#000000", iconId: "markdown" },
  { name: "Mastodon", category: "Tools", badgeUrl: "https://raw.githubusercontent.com/xandemon/developer-icons/main/icons/mastodon.svg", color: "#000000", iconId: "mastodon" },
  { name: "Materialui", category: "Tools", badgeUrl: "https://raw.githubusercontent.com/xandemon/developer-icons/main/icons/materialui.svg", color: "#000000", iconId: "materialui" },
  { name: "Messenger", category: "Tools", badgeUrl: "https://raw.githubusercontent.com/xandemon/developer-icons/main/icons/messenger.svg", color: "#000000", iconId: "messenger" },
  { name: "Meta", category: "Tools", badgeUrl: "https://raw.githubusercontent.com/xandemon/developer-icons/main/icons/meta.svg", color: "#000000", iconId: "meta" },
  { name: "Microsoft", category: "Tools", badgeUrl: "https://raw.githubusercontent.com/xandemon/developer-icons/main/icons/microsoft.svg", color: "#000000", iconId: "microsoft" },
  { name: "Microsoft Sql Server", category: "Tools", badgeUrl: "https://raw.githubusercontent.com/xandemon/developer-icons/main/icons/microsoft-sql-server.svg", color: "#000000", iconId: "microsoft-sql-server" },
  { name: "Miro", category: "Tools", badgeUrl: "https://raw.githubusercontent.com/xandemon/developer-icons/main/icons/miro.svg", color: "#000000", iconId: "miro" },
  { name: "Mochajs", category: "Tools", badgeUrl: "https://raw.githubusercontent.com/xandemon/developer-icons/main/icons/mochajs.svg", color: "#000000", iconId: "mochajs" },
  { name: "Mongodb", category: "Backend", badgeUrl: "https://raw.githubusercontent.com/xandemon/developer-icons/main/icons/mongodb.svg", color: "#000000", iconId: "mongodb" },
  { name: "Mozilla", category: "Tools", badgeUrl: "https://raw.githubusercontent.com/xandemon/developer-icons/main/icons/mozilla.svg", color: "#000000", iconId: "mozilla" },
  { name: "Mysql", category: "Backend", badgeUrl: "https://raw.githubusercontent.com/xandemon/developer-icons/main/icons/mysql.svg", color: "#000000", iconId: "mysql" },
  { name: "Neovim", category: "Tools", badgeUrl: "https://raw.githubusercontent.com/xandemon/developer-icons/main/icons/neovim.svg", color: "#000000", iconId: "neovim" },
  { name: "Nestjs", category: "Backend", badgeUrl: "https://raw.githubusercontent.com/xandemon/developer-icons/main/icons/nestjs.svg", color: "#000000", iconId: "nestjs" },
  { name: "Netlify", category: "DevOps", badgeUrl: "https://raw.githubusercontent.com/xandemon/developer-icons/main/icons/netlify.svg", color: "#000000", iconId: "netlify" },
  { name: "Netlify2", category: "DevOps", badgeUrl: "https://raw.githubusercontent.com/xandemon/developer-icons/main/icons/netlify2.svg", color: "#000000", iconId: "netlify2" },
  { name: "Nextjs", category: "Frontend", badgeUrl: "https://raw.githubusercontent.com/xandemon/developer-icons/main/icons/nextjs.svg", color: "#000000", iconId: "nextjs" },
  { name: "Nextjs Wordmark", category: "Frontend", badgeUrl: "https://raw.githubusercontent.com/xandemon/developer-icons/main/icons/nextjs-wordmark.svg", color: "#000000", iconId: "nextjs-wordmark" },
  { name: "Nim", category: "Backend", badgeUrl: "https://raw.githubusercontent.com/xandemon/developer-icons/main/icons/nim.svg", color: "#000000", iconId: "nim" },
  { name: "Nodejs", category: "Backend", badgeUrl: "https://raw.githubusercontent.com/xandemon/developer-icons/main/icons/nodejs.svg", color: "#000000", iconId: "nodejs" },
  { name: "Notion", category: "Tools", badgeUrl: "https://raw.githubusercontent.com/xandemon/developer-icons/main/icons/notion.svg", color: "#000000", iconId: "notion" },
  { name: "Npm", category: "Tools", badgeUrl: "https://raw.githubusercontent.com/xandemon/developer-icons/main/icons/npm.svg", color: "#000000", iconId: "npm" },
  { name: "Npm Wordmark", category: "Tools", badgeUrl: "https://raw.githubusercontent.com/xandemon/developer-icons/main/icons/npm-wordmark.svg", color: "#000000", iconId: "npm-wordmark" },
  { name: "Numpy", category: "Backend", badgeUrl: "https://raw.githubusercontent.com/xandemon/developer-icons/main/icons/numpy.svg", color: "#000000", iconId: "numpy" },
  { name: "Nuxtjs", category: "Frontend", badgeUrl: "https://raw.githubusercontent.com/xandemon/developer-icons/main/icons/nuxtjs.svg", color: "#000000", iconId: "nuxtjs" },
  { name: "Ocaml", category: "Backend", badgeUrl: "https://raw.githubusercontent.com/xandemon/developer-icons/main/icons/ocaml.svg", color: "#000000", iconId: "ocaml" },
  { name: "Onedrive", category: "Tools", badgeUrl: "https://raw.githubusercontent.com/xandemon/developer-icons/main/icons/onedrive.svg", color: "#000000", iconId: "onedrive" },
  { name: "Openai", category: "Tools", badgeUrl: "https://raw.githubusercontent.com/xandemon/developer-icons/main/icons/openai.svg", color: "#000000", iconId: "openai" },
  { name: "Opera", category: "Frontend", badgeUrl: "https://raw.githubusercontent.com/xandemon/developer-icons/main/icons/opera.svg", color: "#000000", iconId: "opera" },
  { name: "Oracle", category: "Backend", badgeUrl: "https://raw.githubusercontent.com/xandemon/developer-icons/main/icons/oracle.svg", color: "#000000", iconId: "oracle" },
  { name: "Outlook", category: "Tools", badgeUrl: "https://raw.githubusercontent.com/xandemon/developer-icons/main/icons/outlook.svg", color: "#000000", iconId: "outlook" },
  { name: "Pandacss", category: "Frontend", badgeUrl: "https://raw.githubusercontent.com/xandemon/developer-icons/main/icons/pandacss.svg", color: "#000000", iconId: "pandacss" },
  { name: "Photoshop", category: "Tools", badgeUrl: "https://raw.githubusercontent.com/xandemon/developer-icons/main/icons/photoshop.svg", color: "#000000", iconId: "photoshop" },
  { name: "Php", category: "Backend", badgeUrl: "https://raw.githubusercontent.com/xandemon/developer-icons/main/icons/php.svg", color: "#000000", iconId: "php" },
  { name: "Pinia", category: "Frontend", badgeUrl: "https://raw.githubusercontent.com/xandemon/developer-icons/main/icons/pinia.svg", color: "#000000", iconId: "pinia" },
  { name: "Pinterest", category: "Tools", badgeUrl: "https://raw.githubusercontent.com/xandemon/developer-icons/main/icons/pinterest.svg", color: "#000000", iconId: "pinterest" },
  { name: "Pixijs", category: "Tools", badgeUrl: "https://raw.githubusercontent.com/xandemon/developer-icons/main/icons/pixijs.svg", color: "#000000", iconId: "pixijs" },
  { name: "Playwright", category: "Tools", badgeUrl: "https://raw.githubusercontent.com/xandemon/developer-icons/main/icons/playwright.svg", color: "#000000", iconId: "playwright" },
  { name: "Pnpm Dark", category: "Tools", badgeUrl: "https://raw.githubusercontent.com/xandemon/developer-icons/main/icons/pnpm-dark.svg", color: "#000000", iconId: "pnpm-dark" },
  { name: "Pnpm Dark Wordmark", category: "Tools", badgeUrl: "https://raw.githubusercontent.com/xandemon/developer-icons/main/icons/pnpm-dark-wordmark.svg", color: "#000000", iconId: "pnpm-dark-wordmark" },
  { name: "Pnpm Light", category: "Tools", badgeUrl: "https://raw.githubusercontent.com/xandemon/developer-icons/main/icons/pnpm-light.svg", color: "#000000", iconId: "pnpm-light" },
  { name: "Pnpm Light Wordmark", category: "Tools", badgeUrl: "https://raw.githubusercontent.com/xandemon/developer-icons/main/icons/pnpm-light-wordmark.svg", color: "#000000", iconId: "pnpm-light-wordmark" },
  { name: "Postgresql", category: "Backend", badgeUrl: "https://raw.githubusercontent.com/xandemon/developer-icons/main/icons/postgresql.svg", color: "#000000", iconId: "postgresql" },
  { name: "Postman", category: "Tools", badgeUrl: "https://raw.githubusercontent.com/xandemon/developer-icons/main/icons/postman.svg", color: "#000000", iconId: "postman" },
  { name: "Powershell", category: "DevOps", badgeUrl: "https://raw.githubusercontent.com/xandemon/developer-icons/main/icons/powershell.svg", color: "#000000", iconId: "powershell" },
  { name: "Preact", category: "Frontend", badgeUrl: "https://raw.githubusercontent.com/xandemon/developer-icons/main/icons/preact.svg", color: "#000000", iconId: "preact" },
  { name: "Presto", category: "Tools", badgeUrl: "https://raw.githubusercontent.com/xandemon/developer-icons/main/icons/presto.svg", color: "#000000", iconId: "presto" },
  { name: "Prettier", category: "Tools", badgeUrl: "https://raw.githubusercontent.com/xandemon/developer-icons/main/icons/prettier.svg", color: "#000000", iconId: "prettier" },
  { name: "Prisma", category: "Backend", badgeUrl: "https://raw.githubusercontent.com/xandemon/developer-icons/main/icons/prisma.svg", color: "#000000", iconId: "prisma" },
  { name: "Pugjs", category: "Frontend", badgeUrl: "https://raw.githubusercontent.com/xandemon/developer-icons/main/icons/pugjs.svg", color: "#000000", iconId: "pugjs" },
  { name: "Pulumi", category: "DevOps", badgeUrl: "https://raw.githubusercontent.com/xandemon/developer-icons/main/icons/pulumi.svg", color: "#000000", iconId: "pulumi" },
  { name: "Pulumi Dark Wordmark", category: "DevOps", badgeUrl: "https://raw.githubusercontent.com/xandemon/developer-icons/main/icons/pulumi-dark-wordmark.svg", color: "#000000", iconId: "pulumi-dark-wordmark" },
  { name: "Pulumi Light Wordmark", category: "DevOps", badgeUrl: "https://raw.githubusercontent.com/xandemon/developer-icons/main/icons/pulumi-light-wordmark.svg", color: "#000000", iconId: "pulumi-light-wordmark" },
  { name: "Pwa", category: "Tools", badgeUrl: "https://raw.githubusercontent.com/xandemon/developer-icons/main/icons/pwa.svg", color: "#000000", iconId: "pwa" },
  { name: "Python", category: "Backend", badgeUrl: "https://raw.githubusercontent.com/xandemon/developer-icons/main/icons/python.svg", color: "#000000", iconId: "python" },
  { name: "Pytorch", category: "Backend", badgeUrl: "https://raw.githubusercontent.com/xandemon/developer-icons/main/icons/pytorch.svg", color: "#000000", iconId: "pytorch" },
  { name: "Pytorch3d", category: "Backend", badgeUrl: "https://raw.githubusercontent.com/xandemon/developer-icons/main/icons/pytorch3d.svg", color: "#000000", iconId: "pytorch3d" },
  { name: "Qwik", category: "Frontend", badgeUrl: "https://raw.githubusercontent.com/xandemon/developer-icons/main/icons/qwik.svg", color: "#000000", iconId: "qwik" },
  { name: "Radixui", category: "Frontend", badgeUrl: "https://raw.githubusercontent.com/xandemon/developer-icons/main/icons/radixui.svg", color: "#000000", iconId: "radixui" },
  { name: "Rails", category: "Backend", badgeUrl: "https://raw.githubusercontent.com/xandemon/developer-icons/main/icons/rails.svg", color: "#000000", iconId: "rails" },
  { name: "Railway", category: "DevOps", badgeUrl: "https://raw.githubusercontent.com/xandemon/developer-icons/main/icons/railway.svg", color: "#000000", iconId: "railway" },
  { name: "React Query", category: "Frontend", badgeUrl: "https://raw.githubusercontent.com/xandemon/developer-icons/main/icons/react-query.svg", color: "#000000", iconId: "react-query" },
  { name: "Reactjs", category: "Frontend", badgeUrl: "https://raw.githubusercontent.com/xandemon/developer-icons/main/icons/reactjs.svg", color: "#000000", iconId: "reactjs" },
  { name: "Reactrouter", category: "Frontend", badgeUrl: "https://raw.githubusercontent.com/xandemon/developer-icons/main/icons/reactrouter.svg", color: "#000000", iconId: "reactrouter" },
  { name: "Reddit", category: "Tools", badgeUrl: "https://raw.githubusercontent.com/xandemon/developer-icons/main/icons/reddit.svg", color: "#000000", iconId: "reddit" },
  { name: "Reddit Wordmark", category: "Tools", badgeUrl: "https://raw.githubusercontent.com/xandemon/developer-icons/main/icons/reddit-wordmark.svg", color: "#000000", iconId: "reddit-wordmark" },
  { name: "Redhat", category: "Tools", badgeUrl: "https://raw.githubusercontent.com/xandemon/developer-icons/main/icons/redhat.svg", color: "#000000", iconId: "redhat" },
  { name: "Redis", category: "Backend", badgeUrl: "https://raw.githubusercontent.com/xandemon/developer-icons/main/icons/redis.svg", color: "#000000", iconId: "redis" },
  { name: "Redux", category: "Tools", badgeUrl: "https://raw.githubusercontent.com/xandemon/developer-icons/main/icons/redux.svg", color: "#000000", iconId: "redux" },
  { name: "Redux Saga", category: "Tools", badgeUrl: "https://raw.githubusercontent.com/xandemon/developer-icons/main/icons/redux-saga.svg", color: "#000000", iconId: "redux-saga" },
  { name: "Remix Dark", category: "Frontend", badgeUrl: "https://raw.githubusercontent.com/xandemon/developer-icons/main/icons/remix-dark.svg", color: "#000000", iconId: "remix-dark" },
  { name: "Remix Dark Wordmark", category: "Frontend", badgeUrl: "https://raw.githubusercontent.com/xandemon/developer-icons/main/icons/remix-dark-wordmark.svg", color: "#000000", iconId: "remix-dark-wordmark" },
  { name: "Remix Light", category: "Frontend", badgeUrl: "https://raw.githubusercontent.com/xandemon/developer-icons/main/icons/remix-light.svg", color: "#000000", iconId: "remix-light" },
  { name: "Remix Light Wordmark", category: "Frontend", badgeUrl: "https://raw.githubusercontent.com/xandemon/developer-icons/main/icons/remix-light-wordmark.svg", color: "#000000", iconId: "remix-light-wordmark" },
  { name: "Render", category: "DevOps", badgeUrl: "https://raw.githubusercontent.com/xandemon/developer-icons/main/icons/render.svg", color: "#000000", iconId: "render" },
  { name: "Resend", category: "Tools", badgeUrl: "https://raw.githubusercontent.com/xandemon/developer-icons/main/icons/resend.svg", color: "#000000", iconId: "resend" },
  { name: "Rollup", category: "Tools", badgeUrl: "https://raw.githubusercontent.com/xandemon/developer-icons/main/icons/rollup.svg", color: "#000000", iconId: "rollup" },
  { name: "Ruby", category: "Backend", badgeUrl: "https://raw.githubusercontent.com/xandemon/developer-icons/main/icons/ruby.svg", color: "#000000", iconId: "ruby" },
  { name: "Rust Dark", category: "Backend", badgeUrl: "https://raw.githubusercontent.com/xandemon/developer-icons/main/icons/rust-dark.svg", color: "#000000", iconId: "rust-dark" },
  { name: "Rust Light", category: "Backend", badgeUrl: "https://raw.githubusercontent.com/xandemon/developer-icons/main/icons/rust-light.svg", color: "#000000", iconId: "rust-light" },
  { name: "Safari", category: "Frontend", badgeUrl: "https://raw.githubusercontent.com/xandemon/developer-icons/main/icons/safari.svg", color: "#000000", iconId: "safari" },
  { name: "Sass", category: "Frontend", badgeUrl: "https://raw.githubusercontent.com/xandemon/developer-icons/main/icons/sass.svg", color: "#000000", iconId: "sass" },
  { name: "Scala", category: "Backend", badgeUrl: "https://raw.githubusercontent.com/xandemon/developer-icons/main/icons/scala.svg", color: "#000000", iconId: "scala" },
  { name: "Semanticui", category: "Tools", badgeUrl: "https://raw.githubusercontent.com/xandemon/developer-icons/main/icons/semanticui.svg", color: "#000000", iconId: "semanticui" },
  { name: "Serverless", category: "Frontend", badgeUrl: "https://raw.githubusercontent.com/xandemon/developer-icons/main/icons/serverless.svg", color: "#000000", iconId: "serverless" },
  { name: "Shadcnui", category: "Frontend", badgeUrl: "https://raw.githubusercontent.com/xandemon/developer-icons/main/icons/shadcnui.svg", color: "#000000", iconId: "shadcnui" },
  { name: "Sketch", category: "Tools", badgeUrl: "https://raw.githubusercontent.com/xandemon/developer-icons/main/icons/sketch.svg", color: "#000000", iconId: "sketch" },
  { name: "Sketch2", category: "Tools", badgeUrl: "https://raw.githubusercontent.com/xandemon/developer-icons/main/icons/sketch2.svg", color: "#000000", iconId: "sketch2" },
  { name: "Skype", category: "Tools", badgeUrl: "https://raw.githubusercontent.com/xandemon/developer-icons/main/icons/skype.svg", color: "#000000", iconId: "skype" },
  { name: "Slack", category: "Tools", badgeUrl: "https://raw.githubusercontent.com/xandemon/developer-icons/main/icons/slack.svg", color: "#000000", iconId: "slack" },
  { name: "Solidity", category: "Frontend", badgeUrl: "https://raw.githubusercontent.com/xandemon/developer-icons/main/icons/solidity.svg", color: "#000000", iconId: "solidity" },
  { name: "Solidjs", category: "Frontend", badgeUrl: "https://raw.githubusercontent.com/xandemon/developer-icons/main/icons/solidjs.svg", color: "#000000", iconId: "solidjs" },
  { name: "Spring", category: "Backend", badgeUrl: "https://raw.githubusercontent.com/xandemon/developer-icons/main/icons/spring.svg", color: "#000000", iconId: "spring" },
  { name: "Storyblok", category: "Frontend", badgeUrl: "https://raw.githubusercontent.com/xandemon/developer-icons/main/icons/storyblok.svg", color: "#000000", iconId: "storyblok" },
  { name: "Storybook", category: "Tools", badgeUrl: "https://raw.githubusercontent.com/xandemon/developer-icons/main/icons/storybook.svg", color: "#000000", iconId: "storybook" },
  { name: "Stream", category: "Tools", badgeUrl: "https://raw.githubusercontent.com/xandemon/developer-icons/main/icons/stream.svg", color: "#000000", iconId: "stream" },
  { name: "Stylelint", category: "Tools", badgeUrl: "https://raw.githubusercontent.com/xandemon/developer-icons/main/icons/stylelint.svg", color: "#000000", iconId: "stylelint" },
  { name: "Sublime", category: "Tools", badgeUrl: "https://raw.githubusercontent.com/xandemon/developer-icons/main/icons/sublime.svg", color: "#000000", iconId: "sublime" },
  { name: "Supabase", category: "Backend", badgeUrl: "https://raw.githubusercontent.com/xandemon/developer-icons/main/icons/supabase.svg", color: "#000000", iconId: "supabase" },
  { name: "Sveltejs", category: "Frontend", badgeUrl: "https://raw.githubusercontent.com/xandemon/developer-icons/main/icons/sveltejs.svg", color: "#000000", iconId: "sveltejs" },
  { name: "Swagger", category: "Tools", badgeUrl: "https://raw.githubusercontent.com/xandemon/developer-icons/main/icons/swagger.svg", color: "#000000", iconId: "swagger" },
  { name: "Swift", category: "Backend", badgeUrl: "https://raw.githubusercontent.com/xandemon/developer-icons/main/icons/swift.svg", color: "#000000", iconId: "swift" },
  { name: "Tailwindcss", category: "Frontend", badgeUrl: "https://raw.githubusercontent.com/xandemon/developer-icons/main/icons/tailwindcss.svg", color: "#000000", iconId: "tailwindcss" },
  { name: "Telegram", category: "Tools", badgeUrl: "https://raw.githubusercontent.com/xandemon/developer-icons/main/icons/telegram.svg", color: "#000000", iconId: "telegram" },
  { name: "Tensorflow", category: "Tools", badgeUrl: "https://raw.githubusercontent.com/xandemon/developer-icons/main/icons/tensorflow.svg", color: "#000000", iconId: "tensorflow" },
  { name: "Terraform", category: "DevOps", badgeUrl: "https://raw.githubusercontent.com/xandemon/developer-icons/main/icons/terraform.svg", color: "#000000", iconId: "terraform" },
  { name: "Threads Dark", category: "Tools", badgeUrl: "https://raw.githubusercontent.com/xandemon/developer-icons/main/icons/threads-dark.svg", color: "#000000", iconId: "threads-dark" },
  { name: "Threads Light", category: "Tools", badgeUrl: "https://raw.githubusercontent.com/xandemon/developer-icons/main/icons/threads-light.svg", color: "#000000", iconId: "threads-light" },
  { name: "Threejs", category: "Tools", badgeUrl: "https://raw.githubusercontent.com/xandemon/developer-icons/main/icons/threejs.svg", color: "#000000", iconId: "threejs" },
  { name: "Tiktok", category: "Tools", badgeUrl: "https://raw.githubusercontent.com/xandemon/developer-icons/main/icons/tiktok.svg", color: "#000000", iconId: "tiktok" },
  { name: "Tinyhttp", category: "Backend", badgeUrl: "https://raw.githubusercontent.com/xandemon/developer-icons/main/icons/tinyhttp.svg", color: "#000000", iconId: "tinyhttp" },
  { name: "Tor", category: "Tools", badgeUrl: "https://raw.githubusercontent.com/xandemon/developer-icons/main/icons/tor.svg", color: "#000000", iconId: "tor" },
  { name: "TRPC", category: "Tools", badgeUrl: "https://raw.githubusercontent.com/xandemon/developer-icons/main/icons/tRPC.svg", color: "#000000", iconId: "tRPC" },
  { name: "Twitter", category: "Tools", badgeUrl: "https://raw.githubusercontent.com/xandemon/developer-icons/main/icons/twitter.svg", color: "#000000", iconId: "twitter" },
  { name: "Typescript", category: "Frontend", badgeUrl: "https://raw.githubusercontent.com/xandemon/developer-icons/main/icons/typescript.svg", color: "#000000", iconId: "typescript" },
  { name: "Ubuntu", category: "Backend", badgeUrl: "https://raw.githubusercontent.com/xandemon/developer-icons/main/icons/ubuntu.svg", color: "#000000", iconId: "ubuntu" },
  { name: "Unjs", category: "Tools", badgeUrl: "https://raw.githubusercontent.com/xandemon/developer-icons/main/icons/unjs.svg", color: "#000000", iconId: "unjs" },
  { name: "Upwork", category: "Tools", badgeUrl: "https://raw.githubusercontent.com/xandemon/developer-icons/main/icons/upwork.svg", color: "#000000", iconId: "upwork" },
  { name: "Upwork Basic", category: "Tools", badgeUrl: "https://raw.githubusercontent.com/xandemon/developer-icons/main/icons/upwork-basic.svg", color: "#000000", iconId: "upwork-basic" },
  { name: "Upwork Wordmark", category: "Tools", badgeUrl: "https://raw.githubusercontent.com/xandemon/developer-icons/main/icons/upwork-wordmark.svg", color: "#000000", iconId: "upwork-wordmark" },
  { name: "Vagrant", category: "DevOps", badgeUrl: "https://raw.githubusercontent.com/xandemon/developer-icons/main/icons/vagrant.svg", color: "#000000", iconId: "vagrant" },
  { name: "Vercel Dark", category: "DevOps", badgeUrl: "https://raw.githubusercontent.com/xandemon/developer-icons/main/icons/vercel-dark.svg", color: "#000000", iconId: "vercel-dark" },
  { name: "Vercel Dark Wordmark", category: "DevOps", badgeUrl: "https://raw.githubusercontent.com/xandemon/developer-icons/main/icons/vercel-dark-wordmark.svg", color: "#000000", iconId: "vercel-dark-wordmark" },
  { name: "Vercel Light", category: "DevOps", badgeUrl: "https://raw.githubusercontent.com/xandemon/developer-icons/main/icons/vercel-light.svg", color: "#000000", iconId: "vercel-light" },
  { name: "Vercel Light Wordmark", category: "DevOps", badgeUrl: "https://raw.githubusercontent.com/xandemon/developer-icons/main/icons/vercel-light-wordmark.svg", color: "#000000", iconId: "vercel-light-wordmark" },
  { name: "Vim", category: "Tools", badgeUrl: "https://raw.githubusercontent.com/xandemon/developer-icons/main/icons/vim.svg", color: "#000000", iconId: "vim" },
  { name: "Visualbasic", category: "Tools", badgeUrl: "https://raw.githubusercontent.com/xandemon/developer-icons/main/icons/visualbasic.svg", color: "#000000", iconId: "visualbasic" },
  { name: "Vitejs", category: "Tools", badgeUrl: "https://raw.githubusercontent.com/xandemon/developer-icons/main/icons/vitejs.svg", color: "#000000", iconId: "vitejs" },
  { name: "Vitest", category: "Tools", badgeUrl: "https://raw.githubusercontent.com/xandemon/developer-icons/main/icons/vitest.svg", color: "#000000", iconId: "vitest" },
  { name: "Vivaldi", category: "Frontend", badgeUrl: "https://raw.githubusercontent.com/xandemon/developer-icons/main/icons/vivaldi.svg", color: "#000000", iconId: "vivaldi" },
  { name: "Vk", category: "Tools", badgeUrl: "https://raw.githubusercontent.com/xandemon/developer-icons/main/icons/vk.svg", color: "#000000", iconId: "vk" },
  { name: "Vscode", category: "Tools", badgeUrl: "https://raw.githubusercontent.com/xandemon/developer-icons/main/icons/vscode.svg", color: "#000000", iconId: "vscode" },
  { name: "Vuejs", category: "Frontend", badgeUrl: "https://raw.githubusercontent.com/xandemon/developer-icons/main/icons/vuejs.svg", color: "#000000", iconId: "vuejs" },
  { name: "Webassembly", category: "Frontend", badgeUrl: "https://raw.githubusercontent.com/xandemon/developer-icons/main/icons/webassembly.svg", color: "#000000", iconId: "webassembly" },
  { name: "Webpack", category: "Tools", badgeUrl: "https://raw.githubusercontent.com/xandemon/developer-icons/main/icons/webpack.svg", color: "#000000", iconId: "webpack" },
  { name: "Webrtc", category: "Tools", badgeUrl: "https://raw.githubusercontent.com/xandemon/developer-icons/main/icons/webrtc.svg", color: "#000000", iconId: "webrtc" },
  { name: "Whatsapp", category: "Tools", badgeUrl: "https://raw.githubusercontent.com/xandemon/developer-icons/main/icons/whatsapp.svg", color: "#000000", iconId: "whatsapp" },
  { name: "Wordpress", category: "Tools", badgeUrl: "https://raw.githubusercontent.com/xandemon/developer-icons/main/icons/wordpress.svg", color: "#000000", iconId: "wordpress" },
  { name: "X Dark", category: "Tools", badgeUrl: "https://raw.githubusercontent.com/xandemon/developer-icons/main/icons/x-dark.svg", color: "#000000", iconId: "x-dark" },
  { name: "X Light", category: "Tools", badgeUrl: "https://raw.githubusercontent.com/xandemon/developer-icons/main/icons/x-light.svg", color: "#000000", iconId: "x-light" },
  { name: "Xamarin", category: "Tools", badgeUrl: "https://raw.githubusercontent.com/xandemon/developer-icons/main/icons/xamarin.svg", color: "#000000", iconId: "xamarin" },
  { name: "Xd", category: "Tools", badgeUrl: "https://raw.githubusercontent.com/xandemon/developer-icons/main/icons/xd.svg", color: "#000000", iconId: "xd" },
  { name: "Yoga", category: "Tools", badgeUrl: "https://raw.githubusercontent.com/xandemon/developer-icons/main/icons/yoga.svg", color: "#000000", iconId: "yoga" },
  { name: "Youtube", category: "Tools", badgeUrl: "https://raw.githubusercontent.com/xandemon/developer-icons/main/icons/youtube.svg", color: "#000000", iconId: "youtube" },
  { name: "Youtube Wordmark", category: "Tools", badgeUrl: "https://raw.githubusercontent.com/xandemon/developer-icons/main/icons/youtube-wordmark.svg", color: "#000000", iconId: "youtube-wordmark" },
  { name: "Zen", category: "Tools", badgeUrl: "https://raw.githubusercontent.com/xandemon/developer-icons/main/icons/zen.svg", color: "#000000", iconId: "zen" },
  { name: "Zod", category: "Tools", badgeUrl: "https://raw.githubusercontent.com/xandemon/developer-icons/main/icons/zod.svg", color: "#000000", iconId: "zod" },
];

export const CATEGORIES = ["Frontend", "Backend", "DevOps", "Tools"] as const;
